name = "fleury_dot_net"
type = "webpack"
account_id = "2f7c5048825c2c6f0c504fa10bd10651"
workers_dev = false
zone_id = "f2eed56cdf8acaeadebd75d455c4436f"
route = "fleury.net/workers-site"

[site]
bucket = "./public"
entry-point = "workers-site"
